import { Product, ProductVariant } from "./types";
import { applyInventorySnapshot } from "./inventory-snapshot";
import { getQuantityUnitPrice } from "./quantity-pricing";

/**
 * Mock catalog shaped to mirror the WooCommerce REST/Store API product
 * schema (id, slug, sku, price, stock_status, categories, meta_data for
 * purity/mass/batch). Swap `getProducts` / `getProductBySlug` for real
 * fetches against the WooCommerce API once the WordPress site is live -
 * see lib/woocommerce.ts.
 *
 * Every mg/iu/mcg strength of a compound is still its own Product entry
 * (its own slug, sku, price, real page - needed for direct links, SEO,
 * and per-dose COA/batch data). Siblings sharing a base compound carry an
 * identical `variants` array (see the *_VARIANTS consts below) for fast
 * switching on product pages, while every in-stock dose keeps its own card
 * in the main shop grid.
 *
 * "EVLV-3" is the site's compliant name for Retatrutide - do not rename to
 * "Retatrutide" anywhere in copy, slugs, or SKUs.
 */

const BPC_157_VARIANTS: ProductVariant[] = [
  { slug: "bpc-157-10mg", label: "10mg", price: 49.99, inStock: true },
  { slug: "bpc-157-5mg", label: "5mg", price: 39.99, inStock: true },
  { slug: "bpc-157-20mg", label: "20mg", price: 89.99, inStock: true },
];

const TB_500_VARIANTS: ProductVariant[] = [
  { slug: "tb-500-10mg", label: "10mg", price: 69.99, inStock: true },
  { slug: "tb-500-5mg", label: "5mg", price: 44.99, inStock: true },
  { slug: "tb-500-20mg", label: "20mg", price: 129.99, inStock: true },
];

const BPC_TB_BLEND_VARIANTS: ProductVariant[] = [
  { slug: "bpc-tb-500-blend-10mg", label: "10mg", price: 74.99, inStock: true },
  { slug: "bpc-tb-500-blend-20mg", label: "20mg", price: 109.99, inStock: true },
];

const EVLV3_VARIANTS: ProductVariant[] = [
  { slug: "evlv-3-10mg", label: "10mg", price: 74.99, inStock: true },
  { slug: "evlv-3-15mg", label: "15mg", price: 129.99, inStock: true },
  { slug: "evlv-3-30mg", label: "30mg", price: 189.99, inStock: true },
  { slug: "evlv-3-60mg", label: "60mg", price: 349.99, inStock: true },
];

const TESAMORELIN_VARIANTS: ProductVariant[] = [
  { slug: "tesamorelin-10mg", label: "10mg", price: 94.99, inStock: true },
  { slug: "tesamorelin-20mg", label: "20mg", price: 149.99, inStock: true },
];

const MOTS_C_VARIANTS: ProductVariant[] = [
  { slug: "mots-c-10mg", label: "10mg", price: 59.99, inStock: true },
  { slug: "mots-c-40mg", label: "40mg", price: 149.99, inStock: true },
];

const CJC_IPA_BLEND_VARIANTS: ProductVariant[] = [
  { slug: "cjc-ipa-blend-10mg", label: "10mg", price: 74.99, inStock: true },
  { slug: "cjc-ipa-blend-20mg", label: "20mg", price: 129.99, inStock: true },
];

const EVLV1_VARIANTS: ProductVariant[] = [
  { slug: "evlv-1-5mg", label: "5mg", price: 49.99, inStock: true },
  { slug: "evlv-1-10mg", label: "10mg", price: 74.99, inStock: true },
];

const EVLV2_VARIANTS: ProductVariant[] = [
  { slug: "evlv-2-10mg", label: "10mg", price: 69.99, inStock: true },
  { slug: "evlv-2-15mg", label: "15mg", price: 89.99, inStock: true },
  { slug: "evlv-2-30mg", label: "30mg", price: 149.99, inStock: true },
  { slug: "evlv-2-60mg", label: "60mg", price: 274.99, inStock: true },
];

export const products: Product[] = [
  // ---- EVLV-3 (Retatrutide) ----
  {
    id: "7",
    slug: "evlv-3-10mg",
    sku: "EVLV3-10",
    name: "GLP3-R 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/evlv-3-10mg.png",
    price: 74.99,
    bulkOption: { qty: 10, price: 599.92, savePercent: 20 },
    purity: "99.34%",
    casNumber: "2381089-83-2",
    avgMass: "9.97 mg",
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    shortDescription: "Tri-agonist research peptide, standard concentration.",
    description:
      "GLP3-R 10mg vial for research protocols. 99.34% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-7184415-P", date: "2026-06-08", status: "PASS" },
    variants: EVLV3_VARIANTS,
  },
  {
    id: "28",
    slug: "evlv-3-15mg",
    sku: "EVLV3-15",
    name: "GLP3-R 15MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/evlv-3-15mg.png",
    price: 129.99,
    bulkOption: { qty: 10, price: 1039.92, savePercent: 20 },
    purity: "99.41%",
    casNumber: "2381089-83-2",
    avgMass: "14.88 mg",
    rating: 4.7,
    reviewCount: 20,
    inStock: true,
    shortDescription: "Tri-agonist research peptide, mid concentration.",
    description:
      "GLP3-R 15mg vial for research protocols. 99.41% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-5244055-P", date: "2026-06-08", status: "PASS" },
    variants: EVLV3_VARIANTS,
  },
  {
    id: "29",
    slug: "evlv-3-30mg",
    sku: "EVLV3-30",
    name: "GLP3-R 30MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/evlv-3-30mg.png",
    price: 189.99,
    bulkOption: { qty: 10, price: 1519.92, savePercent: 20 },
    purity: "99.43%",
    casNumber: "2381089-83-2",
    avgMass: "29.73 mg",
    rating: 4.8,
    reviewCount: 12,
    inStock: true,
    shortDescription: "Tri-agonist research peptide, high concentration.",
    description:
      "GLP3-R 30mg vial for research protocols. 99.43% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-6472318-P", date: "2026-06-08", status: "PASS" },
    variants: EVLV3_VARIANTS,
  },
  {
    id: "30",
    slug: "evlv-3-60mg",
    sku: "EVLV3-60",
    name: "GLP3-R 60MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/evlv-3-60mg.png",
    price: 349.99,
    bulkOption: { qty: 10, price: 2799.92, savePercent: 20 },
    purity: "99.6%",
    casNumber: "2381089-83-2",
    avgMass: "60.1 mg",
    rating: 4.8,
    reviewCount: 9,
    inStock: true,
    shortDescription: "Tri-agonist research peptide, maximum concentration.",
    description:
      "GLP3-R 60mg vial for research protocols. 99.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-EVLV3-60-08", date: "2026-08-16", status: "PASS" },
    variants: EVLV3_VARIANTS,
  },

  // ---- EVLV-1 / EVLV-2 (metabolic; compliant names for Semaglutide / Tirzepatide) ----
  {
    id: "36",
    slug: "evlv-1-5mg",
    sku: "EVLV1-5",
    name: "GLP1-S 5MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/semaglutide-5mg.png",
    price: 49.99,
    bulkOption: { qty: 10, price: 399.92, savePercent: 20 },
    purity: "99.19%",
    casNumber: "910463-68-2",
    avgMass: "5.05 mg",
    rating: 4.7,
    reviewCount: 31,
    inStock: true,
    shortDescription: "GLP-1 receptor agonist research peptide, standard concentration.",
    description: "GLP1-S 5mg vial for research protocols. 99.19% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-4193082-P", date: "2026-06-08", status: "PASS" },
    variants: EVLV1_VARIANTS,
  },
  {
    id: "37",
    slug: "evlv-1-10mg",
    sku: "EVLV1-10",
    name: "GLP1-S 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/semaglutide-10mg.png",
    price: 74.99,
    bulkOption: { qty: 10, price: 599.92, savePercent: 20 },
    purity: "99.4%",
    casNumber: "910463-68-2",
    avgMass: "10.11 mg",
    rating: 4.8,
    reviewCount: 24,
    inStock: true,
    shortDescription: "GLP-1 receptor agonist research peptide, high concentration.",
    description: "GLP1-S 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-SEM10-08", date: "2026-08-24", status: "PASS" },
    variants: EVLV1_VARIANTS,
  },
  {
    id: "38",
    slug: "evlv-2-10mg",
    sku: "EVLV2-10",
    name: "GLP2-T 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tirzepatide-10mg.png",
    price: 69.99,
    bulkOption: { qty: 10, price: 559.92, savePercent: 20 },
    purity: "99.44%",
    casNumber: "2023788-19-2",
    avgMass: "10.08 mg",
    rating: 4.8,
    reviewCount: 37,
    inStock: true,
    shortDescription: "GIP/GLP-1 dual-agonist research peptide, standard concentration.",
    description: "GLP2-T 10mg vial for research protocols. 99.44% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-9109868-P", date: "2026-06-08", status: "PASS" },
    variants: EVLV2_VARIANTS,
  },
  {
    id: "39",
    slug: "evlv-2-15mg",
    sku: "EVLV2-15",
    name: "GLP2-T 15MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tirzepatide-15mg.png",
    price: 89.99,
    bulkOption: { qty: 10, price: 719.92, savePercent: 20 },
    purity: "99.28%",
    casNumber: "2023788-19-2",
    avgMass: "14.96 mg",
    rating: 4.8,
    reviewCount: 15,
    inStock: true,
    shortDescription: "GIP/GLP-1 dual-agonist research peptide, mid concentration.",
    description: "GLP2-T 15mg vial for research protocols. 99.28% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-3795846-P", date: "2026-06-08", status: "PASS" },
    variants: EVLV2_VARIANTS,
  },
  {
    id: "40",
    slug: "evlv-2-30mg",
    sku: "EVLV2-30",
    name: "GLP2-T 30MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tirzepatide-30mg.png",
    price: 149.99,
    bulkOption: { qty: 10, price: 1199.92, savePercent: 20 },
    purity: "99.29%",
    casNumber: "2023788-19-2",
    avgMass: "30.25 mg",
    rating: 4.8,
    reviewCount: 13,
    inStock: true,
    shortDescription: "GIP/GLP-1 dual-agonist research peptide, high concentration.",
    description: "GLP2-T 30mg vial for research protocols. 99.29% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-6006482-P", date: "2026-06-08", status: "PASS" },
    variants: EVLV2_VARIANTS,
  },
  {
    id: "41",
    slug: "evlv-2-60mg",
    sku: "EVLV2-60",
    name: "GLP2-T 60MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tirzepatide-60mg.png",
    price: 274.99,
    bulkOption: { qty: 10, price: 2199.92, savePercent: 20 },
    purity: "99.6%",
    casNumber: "2023788-19-2",
    avgMass: "60.2 mg",
    rating: 4.9,
    reviewCount: 7,
    inStock: true,
    shortDescription: "GIP/GLP-1 dual-agonist research peptide, maximum concentration.",
    description: "GLP2-T 60mg vial for research protocols. 99.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-TIR60-08", date: "2026-08-25", status: "PASS" },
    variants: EVLV2_VARIANTS,
  },

  // ---- BPC-157 ----
  {
    id: "1",
    slug: "bpc-157-5mg",
    sku: "BPC-5",
    name: "BPC-157 5MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/bpc-157-5mg.png",
    price: 39.99,
    bulkOption: { qty: 10, price: 319.92, savePercent: 20 },
    purity: "99.31%",
    casNumber: "137525-51-0",
    avgMass: "5.05 mg",
    rating: 4.8,
    reviewCount: 41,
    inStock: true,
    shortDescription: "Standard-concentration BPC-157 for research protocols.",
    description:
      "BPC-157 5mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-8212693-P", date: "2026-06-08", status: "PASS" },
    variants: BPC_157_VARIANTS,
  },
  {
    id: "2",
    slug: "bpc-157-10mg",
    sku: "BPC-10",
    name: "BPC-157 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/bpc-157-10mg.png",
    price: 49.99,
    bulkOption: { qty: 10, price: 399.92, savePercent: 20 },
    purity: "99.41%",
    casNumber: "137525-51-0",
    avgMass: "9.93 mg",
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    shortDescription: "Higher-concentration BPC-157 for extended research protocols.",
    description:
      "BPC-157 10mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-4152086-P", date: "2026-06-08", status: "PASS" },
    variants: BPC_157_VARIANTS,
  },
  {
    id: "3",
    slug: "bpc-157-20mg",
    sku: "BPC-20",
    name: "BPC-157 20MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/bpc-157-20mg.png",
    price: 89.99,
    bulkOption: { qty: 10, price: 719.92, savePercent: 20 },
    purity: "99.9%",
    casNumber: "137525-51-0",
    avgMass: "20.4 mg",
    rating: 4.9,
    reviewCount: 33,
    inStock: true,
    shortDescription: "High-concentration BPC-157 for extended research protocols.",
    description:
      "BPC-157 20mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-BPC20-08", date: "2026-08-11", status: "PASS" },
    variants: BPC_157_VARIANTS,
  },

  // ---- TB-500 ----
  {
    id: "4",
    slug: "tb-500-5mg",
    sku: "TB-5",
    name: "TB-500 5MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tb-500-5mg.png",
    price: 44.99,
    bulkOption: { qty: 10, price: 359.92, savePercent: 20 },
    purity: "99.59%",
    casNumber: "77591-33-4",
    avgMass: "5.05 mg",
    rating: 4.7,
    reviewCount: 27,
    inStock: true,
    shortDescription: "Standard-concentration TB-500 for research protocols.",
    description:
      "TB-500 5mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-8212693-P", date: "2026-06-08", status: "PASS" },
    variants: TB_500_VARIANTS,
  },
  {
    id: "5",
    slug: "tb-500-10mg",
    sku: "TB-10",
    name: "TB-500 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tb-500-10mg.png",
    price: 69.99,
    bulkOption: { qty: 10, price: 559.92, savePercent: 20 },
    purity: "99.65%",
    casNumber: "77591-33-4",
    avgMass: "9.93 mg",
    rating: 4.8,
    reviewCount: 52,
    inStock: true,
    shortDescription: "Higher-concentration TB-500 for extended research protocols.",
    description:
      "TB-500 10mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-4152086-P", date: "2026-06-08", status: "PASS" },
    variants: TB_500_VARIANTS,
  },
  {
    id: "6",
    slug: "tb-500-20mg",
    sku: "TB-20",
    name: "TB-500 20MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tb-500-20mg.png",
    price: 129.99,
    bulkOption: { qty: 10, price: 1039.92, savePercent: 20 },
    purity: "99.1%",
    casNumber: "77591-33-4",
    avgMass: "20.3 mg",
    rating: 4.8,
    reviewCount: 19,
    inStock: true,
    shortDescription: "High-concentration TB-500 for extended research protocols.",
    description:
      "TB-500 20mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-TB20-08", date: "2026-08-13", status: "PASS" },
    variants: TB_500_VARIANTS,
  },

  // ---- BPC-157 / TB-500 blend ----
  {
    id: "8",
    slug: "bpc-tb-500-blend-10mg",
    sku: "BB-10",
    name: "BPC-157 / TB-500 BLEND 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    format: "blend",
    image: "/images/products/bpc-tb-500-blend-10mg.png",
    price: 74.99,
    bulkOption: { qty: 10, price: 599.92, savePercent: 20 },
    purity: "99.31% BPC-157 / 99.59% TB-500",
    casNumber: "137525-51-0, 77591-33-4",
    avgMass: "10.1 mg",
    rating: 4.8,
    reviewCount: 22,
    inStock: true,
    shortDescription: "Pre-combined BPC-157 and TB-500 blend for research convenience.",
    description:
      "BPC-157 / TB-500 10mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-8212693-P", date: "2026-06-08", status: "PASS" },
    variants: BPC_TB_BLEND_VARIANTS,
  },
  {
    id: "9",
    slug: "bpc-tb-500-blend-20mg",
    sku: "BB-20",
    name: "BPC-157 / TB-500 BLEND 20MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    format: "blend",
    image: "/images/products/bpc-tb-500-blend-20mg.png",
    price: 109.99,
    bulkOption: { qty: 10, price: 879.92, savePercent: 20 },
    purity: "99.41% BPC-157 / 99.65% TB-500",
    casNumber: "137525-51-0, 77591-33-4",
    avgMass: "19.86 mg",
    rating: 4.8,
    reviewCount: 14,
    inStock: true,
    shortDescription: "Pre-combined BPC-157 and TB-500 blend for research convenience.",
    description:
      "BPC-157 / TB-500 20mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-4152086-P", date: "2026-06-08", status: "PASS" },
    variants: BPC_TB_BLEND_VARIANTS,
  },

  // ---- Tesamorelin ----
  {
    id: "10",
    slug: "tesamorelin-10mg",
    sku: "TES-10",
    name: "TESAMORELIN 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tesamorelin-10mg.png",
    price: 94.99,
    bulkOption: { qty: 10, price: 759.92, savePercent: 20 },
    purity: "99.86%",
    casNumber: "218949-48-5",
    avgMass: "11.83 mg",
    rating: 4.6,
    reviewCount: 29,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description:
      "Tesamorelin 10mg vial for research protocols. 99.86% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-TES10-07", date: "2026-07-18", status: "PASS" },
    variants: TESAMORELIN_VARIANTS,
  },
  {
    id: "31",
    slug: "tesamorelin-20mg",
    sku: "TES-20",
    name: "TESAMORELIN 20MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/tesamorelin-20mg.png",
    price: 149.99,
    bulkOption: { qty: 10, price: 1199.92, savePercent: 20 },
    purity: "99.7%",
    casNumber: "218949-48-5",
    avgMass: "20.2 mg",
    rating: 4.7,
    reviewCount: 11,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, high concentration.",
    description:
      "Tesamorelin 20mg vial for research protocols. 99.7% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-TES20-08", date: "2026-08-17", status: "PASS" },
    variants: TESAMORELIN_VARIANTS,
  },

  // ---- GHK-Cu ----
  {
    id: "17",
    slug: "ghk-cu-50mg",
    sku: "GHK-50",
    name: "GHK-CU 50MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/ghk-cu-50mg.png",
    price: 39.99,
    bulkOption: { qty: 10, price: 319.92, savePercent: 20 },
    purity: "99.4%",
    casNumber: "89030-95-5",
    avgMass: "50.1 mg",
    rating: 4.7,
    reviewCount: 24,
    inStock: true,
    shortDescription: "Copper-peptide research compound, standard concentration.",
    description: "GHK-Cu 50mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-GHK50-08", date: "2026-08-16", status: "PASS" },
  },

  // ---- MOTS-c ----
  {
    id: "18",
    slug: "mots-c-10mg",
    sku: "MOT-10",
    name: "MOTS-C 10MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/mots-c-10mg.png",
    price: 59.99,
    bulkOption: { qty: 10, price: 479.92, savePercent: 20 },
    purity: "99.53%",
    casNumber: "1627580-64-6",
    avgMass: "9.82 mg",
    rating: 4.8,
    reviewCount: 17,
    inStock: true,
    shortDescription: "Mitochondrial-derived peptide, standard concentration.",
    description: "MOTS-c 10mg vial for research protocols. 99.53% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-7058391-P", date: "2026-06-08", status: "PASS" },
    variants: MOTS_C_VARIANTS,
  },
  {
    id: "32",
    slug: "mots-c-40mg",
    sku: "MOT-40",
    name: "MOTS-C 40MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/mots-c-40mg.png",
    price: 149.99,
    bulkOption: { qty: 10, price: 1199.92, savePercent: 20 },
    purity: "99.3%",
    casNumber: "1627580-64-6",
    avgMass: "40.2 mg",
    rating: 4.8,
    reviewCount: 8,
    inStock: true,
    shortDescription: "Mitochondrial-derived peptide, high concentration.",
    description: "MOTS-c 40mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-MOTS40-08", date: "2026-08-18", status: "PASS" },
    variants: MOTS_C_VARIANTS,
  },

  // ---- Thymosin Alpha-1 ----
  {
    id: "21",
    slug: "thymosin-alpha-1-5mg",
    sku: "TA1-5",
    name: "THYMOSIN ALPHA-1 5MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/thymosin-alpha-1-5mg.png",
    price: 44.99,
    bulkOption: { qty: 10, price: 359.92, savePercent: 20 },
    purity: "99.5%",
    casNumber: "62304-98-7",
    avgMass: "5.06 mg",
    rating: 4.7,
    reviewCount: 21,
    inStock: true,
    shortDescription: "Immune-modulating research peptide, standard concentration.",
    description: "Thymosin Alpha-1 5mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-TA15-08", date: "2026-08-19", status: "PASS" },
  },

  // ---- GLOW / KLOW blends ----
  {
    id: "23",
    slug: "glow-70mg",
    sku: "GW-70",
    name: "GLOW 70MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    format: "blend",
    image: "/images/products/glow-70mg.png",
    price: 139.99,
    bulkOption: { qty: 10, price: 1119.92, savePercent: 20 },
    purity: "99.45% BPC-157 / 99.16% TB-500 / 99.54% GHK-Cu",
    casNumber: "89030-95-5, 137525-51-0, 77591-33-4",
    avgMass: "71.45 mg",
    rating: 4.7,
    reviewCount: 19,
    inStock: true,
    shortDescription: "Pre-combined cellular-support blend for research convenience.",
    description: "GLOW 70mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-9377026-P", date: "2026-06-08", status: "PASS" },
  },
  {
    id: "25",
    slug: "klow-80mg",
    sku: "KW-80",
    name: "KLOW 80MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    format: "blend",
    image: "/images/products/klow-80mg.png",
    price: 149.99,
    bulkOption: { qty: 10, price: 1199.92, savePercent: 20 },
    avgMass: "80.2 mg",
    casNumber: "89030-95-5, 67727-97-3, 137525-51-0, 77591-33-4",
    rating: 4.8,
    reviewCount: 15,
    inStock: true,
    shortDescription: "Pre-combined cellular-support blend for research convenience.",
    description: "KLOW 80mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-KLOW80-08", date: "2026-08-21", status: "PASS" },
  },

  // ---- Selank / Semax (cognition) ----
  {
    id: "26",
    slug: "selank-10mg",
    sku: "SEL-10",
    name: "SELANK 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/selank-10mg.png",
    price: 49.99,
    bulkOption: { qty: 10, price: 399.92, savePercent: 20 },
    purity: "99.4%",
    casNumber: "129954-34-3",
    avgMass: "10.08 mg",
    rating: 4.7,
    reviewCount: 18,
    inStock: true,
    shortDescription: "Anxiolytic peptide research compound, standard concentration.",
    description: "Selank 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-SEL10-08", date: "2026-08-22", status: "PASS" },
  },
  {
    id: "33",
    slug: "semax-10mg",
    sku: "SMX-10",
    name: "SEMAX 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/semax-10mg.png",
    price: 49.99,
    bulkOption: { qty: 10, price: 399.92, savePercent: 20 },
    purity: "99.3%",
    casNumber: "80714-61-0",
    avgMass: "10.06 mg",
    rating: 4.7,
    reviewCount: 16,
    inStock: true,
    shortDescription: "Nootropic peptide research compound, standard concentration.",
    description: "Semax 10mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-SMX10-08", date: "2026-08-22", status: "PASS" },
  },

  // ---- CJC-1295 / Ipamorelin blend ----
  {
    id: "34",
    slug: "cjc-ipa-blend-10mg",
    sku: "CP-10",
    name: "CJC-1295 / IPAMORELIN BLEND 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    format: "blend",
    image: "/images/products/cjc-ipa-blend-10mg.png",
    price: 74.99,
    bulkOption: { qty: 10, price: 599.92, savePercent: 20 },
    purity: "99.28% Ipamorelin / 99.36% CJC-1295",
    casNumber: "863288-34-0, 170851-70-4",
    avgMass: "9.8 mg",
    rating: 4.7,
    reviewCount: 20,
    inStock: true,
    shortDescription: "Pre-combined GHRH-analog blend for research convenience.",
    description: "CJC-1295 / Ipamorelin 10mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-3437208-P", date: "2026-06-08", status: "PASS" },
    variants: CJC_IPA_BLEND_VARIANTS,
  },
  {
    id: "35",
    slug: "cjc-ipa-blend-20mg",
    sku: "CP-20",
    name: "CJC-1295 / IPAMORELIN BLEND 20MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    format: "blend",
    image: "/images/products/cjc-ipa-blend-20mg.png",
    price: 129.99,
    bulkOption: { qty: 10, price: 1039.92, savePercent: 20 },
    avgMass: "20.2 mg",
    casNumber: "863288-34-0, 170851-70-4",
    rating: 4.8,
    reviewCount: 10,
    inStock: true,
    shortDescription: "Pre-combined GHRH-analog blend for research convenience.",
    description: "CJC-1295 / Ipamorelin 20mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-CP20-08", date: "2026-08-23", status: "PASS" },
    variants: CJC_IPA_BLEND_VARIANTS,
  },

  // ---- Ancillaries / hormones ----
  {
    id: "42",
    slug: "aod-9604-10mg",
    sku: "AOD-10",
    name: "AOD-9604 10MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/aod-9604-10mg.png",
    price: 64.99,
    bulkOption: { qty: 10, price: 519.92, savePercent: 20 },
    purity: "99.1%",
    casNumber: "221231-10-3",
    avgMass: "10.09 mg",
    rating: 4.6,
    reviewCount: 13,
    inStock: true,
    shortDescription: "Modified hGH-fragment research peptide, standard concentration.",
    description: "AOD-9604 10mg vial for research protocols. 99.1% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-AOD10-08", date: "2026-08-19", status: "PASS" },
  },
  {
    id: "43",
    slug: "cartalax-20mg",
    sku: "CART-20",
    name: "CARTALAX 20MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/cartalax-20mg.png",
    price: 59.99,
    bulkOption: { qty: 10, price: 479.92, savePercent: 20 },
    purity: "99.4%",
    casNumber: "85806-95-7",
    avgMass: "20.1 mg",
    rating: 4.5,
    reviewCount: 6,
    inStock: true,
    shortDescription: "Cartilage-tissue research peptide, standard concentration.",
    description: "Cartalax 20mg vial for research protocols. 98.9% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-CART20-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "46",
    slug: "igf-1-lr3-1mg",
    sku: "IGF1-1",
    name: "IGF-1 LR3 1MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/igf-1-lr3-1mg.png",
    price: 89.99,
    bulkOption: { qty: 10, price: 719.92, savePercent: 20 },
    purity: "99.0%",
    casNumber: "143045-27-6",
    avgMass: "1.02 mg",
    rating: 4.7,
    reviewCount: 14,
    inStock: true,
    shortDescription: "Long-acting IGF-1 analog research compound, standard concentration.",
    description: "IGF-1 LR3 1mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-IGF1-08", date: "2026-08-20", status: "PASS" },
  },
  {
    id: "47",
    slug: "kpv-10mg",
    sku: "KPV-10",
    name: "KPV 10MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/kpv-10mg.png",
    price: 69.99,
    bulkOption: { qty: 10, price: 559.92, savePercent: 20 },
    purity: "99.28%",
    casNumber: "67727-97-3",
    avgMass: "10.15 mg",
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    shortDescription: "Anti-inflammatory tripeptide research compound, standard concentration.",
    description: "KPV 10mg vial for research protocols. 99.28% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "MSV-4451178-P", date: "2026-06-08", status: "PASS" },
  },
  {
    id: "49",
    slug: "melanotan-ii-10mg",
    sku: "MT2-10",
    name: "MELANOTAN II 10MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/melanotan-ii-10mg.png",
    price: 39.99,
    bulkOption: { qty: 10, price: 319.92, savePercent: 20 },
    purity: "99.0%",
    casNumber: "121062-08-6",
    avgMass: "10.06 mg",
    rating: 4.5,
    reviewCount: 16,
    inStock: true,
    shortDescription: "Melanocortin research peptide, standard concentration.",
    description: "Melanotan II 10mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-MT210-08", date: "2026-08-21", status: "PASS" },
  },
  {
    id: "50",
    slug: "nad-500mg",
    sku: "NAD-500",
    name: "NAD+ 500MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/nad-500mg.png",
    price: 64.99,
    bulkOption: { qty: 10, price: 519.92, savePercent: 20 },
    purity: "99.3%",
    casNumber: "53-84-9",
    avgMass: "500.4 mg",
    rating: 4.7,
    reviewCount: 22,
    inStock: true,
    shortDescription: "Cellular-energy cofactor research compound, standard concentration.",
    description: "NAD+ 500mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-NAD500-08", date: "2026-08-21", status: "PASS" },
  },
  {
    id: "51",
    slug: "oxytocin-10mg",
    sku: "OXY-10",
    name: "OXYTOCIN 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/oxytocin-10mg.png",
    price: 39.99,
    bulkOption: { qty: 10, price: 319.92, savePercent: 20 },
    purity: "99.0%",
    casNumber: "50-56-6",
    avgMass: "10.04 mg",
    rating: 4.6,
    reviewCount: 10,
    inStock: true,
    shortDescription: "Neuropeptide research compound, standard concentration.",
    description: "Oxytocin 10mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-OXY10-08", date: "2026-08-22", status: "PASS" },
  },
  {
    id: "52",
    slug: "pt-141-10mg",
    sku: "PT-10",
    name: "PT-141 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/pt-141-10mg.png",
    price: 39.99,
    bulkOption: { qty: 10, price: 319.92, savePercent: 20 },
    purity: "99.1%",
    casNumber: "189691-06-3",
    avgMass: "10.07 mg",
    rating: 4.6,
    reviewCount: 25,
    inStock: true,
    shortDescription: "Melanocortin research peptide, standard concentration.",
    description: "PT-141 10mg vial for research protocols. 99.1% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-PT10-08", date: "2026-08-22", status: "PASS" },
  },
  {
    id: "53",
    slug: "ss-31-10mg",
    sku: "SS31-10",
    name: "SS-31 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/ss-31-10mg.png",
    price: 45.0,
    bulkOption: { qty: 10, price: 360.0, savePercent: 20 },
    purity: "99.4%",
    casNumber: "736992-21-5",
    avgMass: "10.03 mg",
    rating: 4.8,
    reviewCount: 14,
    inStock: true,
    shortDescription: "Mitochondria-targeted research peptide, standard concentration.",
    description: "SS-31 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
    batch: { code: "EVLV-SS3110-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "54",
    slug: "cerebrolysin-60mg",
    sku: "CBL60",
    name: "CEREBROLYSIN 60MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    price: 54.99,
    bulkOption: { qty: 10, price: 439.92, savePercent: 20 },
    casNumber: "12656-61-0",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    shortDescription: "Cerebrolysin research material in a 60mg vial format.",
    description: "Cerebrolysin 60mg, supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
  },
  {
    id: "55",
    slug: "korean-pink-glutathione-1200mg",
    sku: "PG1200",
    name: "KOREAN PINK GLUTATHIONE 1200MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    price: 59.99,
    bulkOption: { qty: 10, price: 479.92, savePercent: 20 },
    casNumber: "70-18-8",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    shortDescription: "Glutathione research material in a 1200mg vial format.",
    description: "Korean Pink Glutathione 1200mg, supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Case Pricing Available"],
  },
  {
    id: "56",
    slug: "bacteriostatic-water-30ml",
    sku: "BAC30",
    name: "HOSPIRA BACTERIOSTATIC WATER 30ML",
    category: "ancillaries",
    categoryLabel: "Research Supplies",
    format: "supplies",
    image: "/images/products/generated-v1/bacteriostatic-water-30ml.png",
    price: 25,
    rating: 0,
    reviewCount: 0,
    inStock: true,
    shortDescription: "30mL bacteriostatic water vial for laboratory preparation workflows.",
    description: "Hospira bacteriostatic water 30mL, supplied for laboratory research use only.",
    storage: "Store according to the manufacturer's labeled conditions.",
  },
];

export function getProducts() {
  return applyInventorySnapshot(products).map(withQuantityPricing);
}

/** Normalize every catalog source to the same public quantity offer. Live
 * inventory can change a vial price without leaving an old case total behind. */
export function withQuantityPricing(product: Product): Product {
  const savePercent = 10;
  const qty = 10;
  return {
    ...product,
    bulkOption: {
      qty,
      savePercent,
      price: Number((getQuantityUnitPrice(product.price, qty) * qty).toFixed(2)),
    },
  };
}

export function getFeaturedProducts() {
  // EVLV-3/EVLV-2/EVLV-1 (the metabolic-research trio) lead as top products per
  // request -- order here is deliberate, not just a filter, since
  // FeaturedProducts renders these in array order.
  const inventoryProducts = getProducts();
  const order = ["evlv-3-10mg", "evlv-2-10mg", "evlv-1-5mg", "aod-9604-10mg"];
  return order
    .map((slug) => inventoryProducts.find((p) => p.slug === slug))
    .filter((p): p is Product => Boolean(p?.inStock));
}

export function getProductBySlug(slug: string) {
  return getProducts().find((p) => p.slug === slug);
}

/**
 * Every published, in-stock SKU gets its own shop card. Dose variants keep
 * their own pages and cards instead of being collapsed into one representative
 * compound. When a resolved catalog is provided, preserve its live Google/CRM
 * stock state; only the static default needs the bundled inventory snapshot.
 */
export function getShopListProducts(source?: Product[]) {
  const catalog = source ?? applyInventorySnapshot(products);
  return catalog.filter((product) => product.inStock);
}

export function getRelatedProducts(slug: string, limit = 4) {
  const current = getProductBySlug(slug);
  if (!current) return [];
  return getProducts()
    .filter((p) => p.slug !== slug && p.category === current.category && p.inStock)
    .slice(0, limit);
}

export const categories: { value: Product["category"] | "all"; label: string }[] = [
  { value: "all", label: "All Research" },
  { value: "peptides", label: "Peptide Research" },
  { value: "ancillaries", label: "Ancillary Research" },
];

export const formats: { value: NonNullable<Product["format"]> | "all"; label: string }[] = [
  { value: "all", label: "All Formats" },
  { value: "blend", label: "Blends" },
  { value: "supplies", label: "Supplies" },
  { value: "oral", label: "Oral / Capsules" },
  { value: "nasal", label: "Nasal Sprays" },
  { value: "device", label: "Multi-Dose Cartridges" },
];
